name: Sync Docker Hub Image to Private Registry

on:
  workflow_dispatch: # 可以手动触发，也可改为 schedule 或 push
  inputs:
      sourceImageName:
        description: "sourceImageName"
        required: true
        default: "sourceImageName"
      targetImageName:
        description: "targetImageName"
        required: true
        default: "targetImageName"

env:
  source_image_name: ${{ github.event.inputs.sourceImageName }}
  target_image_name: ${{ github.event.inputs.targetImageName }}

jobs:
  sync-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        
      - name: show image name
        run: echo "$source_image_name" 
        
      - name: Log in to Private Registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_SERVER }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Pull image from Docker Hub
        run: docker pull $source_image_name

      - name: Tag image for Private Registry
        run: docker tag $source_image_name ${{ secrets.REGISTRY_SERVER }}/hu_vw/$target_image_name

      - name: Push image to Private Registry
        run: docker push ${{ secrets.REGISTRY_SERVER }}/hu_vw/$target_image_name
