name: Sync Docker Hub Image to Private Registry

on:
  workflow_dispatch: # 可以手动触发，也可改为 schedule 或 push

jobs:
  sync-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        
      - name: show variables
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" 
        
      - name: Log in to Private Registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_SERVER }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Pull image from Docker Hub
        run: docker pull ghcr.io/open-webui/open-webui:main

      - name: Tag image for Private Registry
        run: docker tag postgres:latest ${{ secrets.REGISTRY_SERVER }}/hu_vw/postgres:latest

      - name: Push image to Private Registry
        run: docker push ${{ secrets.REGISTRY_SERVER }}/hu_vw/postgres:latest
